### ISSUE TITLE
Image scale selector doesn't work for Batch Upscayl

### ISSUE THREAD

**Issue by dotxyzgaming** [upscayl/upscayl#478]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🚫 File Operation Cancelled
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Pakis\Downloads\set1
🖼 Selected Folder Path:  C:\Users\Pakis\Downloads\set1
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Pakis\Downloads\set1,-o,C:\Users\Pakis\Downloads\set1_upscayled_ultrasharp_x2,-s,4,-m,G:\upscayl\resources\models,-n,ultrasharp,,,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 NVIDIA GeForce GTX 1060 6GB]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1060 6GB]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1060 6GB]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1060 6GB]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.52%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.03%

🚧 FOLDER_UPSCAYL_PROGRESS:  2.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  4.55%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.06%

🚧 FOLDER_UPSCAYL_PROGRESS:  4.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  7.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  9.09%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.61%

🚧 FOLDER_UPSCAYL_PROGRESS:  7.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  12.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.64%

🚧 FOLDER_UPSCAYL_PROGRESS:  9.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.15%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  12.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  18.18%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  19.70%

🚧 FOLDER_UPSCAYL_PROGRESS:  14.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  21.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.73%

🚧 FOLDER_UPSCAYL_PROGRESS:  24.24%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.76%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  27.27%

🚧 FOLDER_UPSCAYL_PROGRESS:  17.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  28.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  18.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  30.30%

🚧 FOLDER_UPSCAYL_PROGRESS:  19.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  31.82%

🚧 FOLDER_UPSCAYL_PROGRESS:  20.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  21.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  34.85%

🚧 FOLDER_UPSCAYL_PROGRESS:  23.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  36.36%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  37.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  26.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  39.39%

🚧 FOLDER_UPSCAYL_PROGRESS:  27.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  40.91%

🚧 FOLDER_UPSCAYL_PROGRESS:  28.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  42.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  29.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  43.94%

🚧 FOLDER_UPSCAYL_PROGRESS:  30.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  45.45%

🚧 FOLDER_UPSCAYL_PROGRESS:  31.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  46.97%

🚧 FOLDER_UPSCAYL_PROGRESS:  32.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  48.48%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  51.52%

🚧 FOLDER_UPSCAYL_PROGRESS:  34.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  53.03%

🚧 FOLDER_UPSCAYL_PROGRESS:  35.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  54.55%

🚧 FOLDER_UPSCAYL_PROGRESS:  36.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  56.06%

🚧 FOLDER_UPSCAYL_PROGRESS:  37.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  57.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  38.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  59.09%

🚧 FOLDER_UPSCAYL_PROGRESS:  39.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  60.61%

🚧 FOLDER_UPSCAYL_PROGRESS:  40.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  62.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  63.64%

🚧 FOLDER_UPSCAYL_PROGRESS:  42.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  65.15%

🚧 FOLDER_UPSCAYL_PROGRESS:  43.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  45.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  68.18%

🚧 FOLDER_UPSCAYL_PROGRESS:  46.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  69.70%

🚧 FOLDER_UPSCAYL_PROGRESS:  47.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  71.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  48.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  72.73%

🚧 FOLDER_UPSCAYL_PROGRESS:  74.24%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.76%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.27%

🚧 FOLDER_UPSCAYL_PROGRESS:  51.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  78.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  52.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  80.30%

🚧 FOLDER_UPSCAYL_PROGRESS:  53.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  81.82%

🚧 FOLDER_UPSCAYL_PROGRESS:  54.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  56.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  57.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  84.85%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  86.36%

🚧 FOLDER_UPSCAYL_PROGRESS:  59.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  87.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  60.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  89.39%

🚧 FOLDER_UPSCAYL_PROGRESS:  61.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  90.91%

🚧 FOLDER_UPSCAYL_PROGRESS:  62.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  92.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  63.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  93.94%

🚧 FOLDER_UPSCAYL_PROGRESS:  64.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  95.45%

🚧 FOLDER_UPSCAYL_PROGRESS:  65.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  96.97%

🚧 FOLDER_UPSCAYL_PROGRESS:  98.48%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  67.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  68.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  2.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  69.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  70.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  4.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  71.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  72.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  73.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  7.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  76.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  9.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  78.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  79.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  12.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  80.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  81.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  14.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  82.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  84.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  17.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  18.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  86.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  19.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  87.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  20.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  21.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  89.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  90.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  23.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  92.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  26.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  93.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  27.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  94.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  28.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  95.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  29.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  96.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  30.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  97.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  31.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  98.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  32.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.64%

🚧 FOLDER_UPSCAYL_PROGRESS:  34.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.28%

🚧 FOLDER_UPSCAYL_PROGRESS:  35.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  36.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  2.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  37.50%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  38.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.85%

🚧 FOLDER_UPSCAYL_PROGRESS:  39.58%

🚧 FOLDER_UPSCAYL_PROGRESS:  4.49%

🚧 FOLDER_UPSCAYL_PROGRESS:  40.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.13%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.77%

🚧 FOLDER_UPSCAYL_PROGRESS:  42.71%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.41%

🚧 FOLDER_UPSCAYL_PROGRESS:  43.75%

🚧 FOLDER_UPSCAYL_PROGRESS:  7.05%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.79%

🚧 FOLDER_UPSCAYL_PROGRESS:  7.69%

🚧 FOLDER_UPSCAYL_PROGRESS:  45.83%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  46.88%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.97%

🚧 FOLDER_UPSCAYL_PROGRESS:  47.92%

🚧 FOLDER_UPSCAYL_PROGRESS:  9.62%

🚧 FOLDER_UPSCAYL_PROGRESS:  48.96%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.26%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.90%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.54%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  12.18%

🚧 FOLDER_UPSCAYL_PROGRESS:  51.04%

🚧 FOLDER_UPSCAYL_PROGRESS:  12.82%

🚧 FOLDER_UPSCAYL_PROGRESS:  52.08%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  53.12%

🚧 FOLDER_UPSCAYL_PROGRESS:  14.10%

🚧 FOLDER_UPSCAYL_PROGRESS:  54.17%

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
🚧 FOLDER_UPSCAYL_PROGRESS:  14.74%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.21%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.38%

🚧 FOLDER_UPSCAYL_PROGRESS:  56.25%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.03%

🚧 FOLDER_UPSCAYL_PROGRESS:  57.29%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  59.38%

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  60.42%

🚧 FOLDER_UPSCAYL_PROGRESS:  17.31%

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
🚧 FOLDER_UPSCAYL_PROGRESS:  61.46%

🚧 FOLDER_UPSCAYL_PROGRESS:  17.95%

🚧 FOLDER_UPSCAYL_PROGRESS:  62.50%
```

### Describe the Bug

Image Scale always doing 4x upscale even 1x 2x 3x selected on batch file

When I select one image and 2x upscale it work fine and 2x upscale the image 

but in batch upload when i select 1x, 2x, 3x it always do 4x upscale

### To Reproduce

make a folder put 3-4 images in it
select a folder in batch upscale
change image scale to 2x
upscale it it will do 4x

### Version/Commit Hash

2.8.1

### OS Specifics

GTX 1060, Windows 10

### Expected Behavior

If I select 2x it have to be upscale 2x like it do in single selection. 

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/140352467/d7890c6c-c11d-4067-b7d4-3d57a7ae822f)

**Comment by NayamAmarshe** [comment]
Oh that's weird. I'll check the code again. Thank you for reporting!

**Comment by NayamAmarshe** [comment]
Oh that's weird. I'll check the code again. Thank you for reporting!

**Comment by NayamAmarshe** [comment]
I've fixed this issue

**Comment by iamgabereal** [comment]
As of v2.8.6 today, the same issue persists for me.

I set the scale to 2x in settings, upscale a single image and all is good. Then the same 2x setting but in a batch, and the results are in 4x instead.

**Comment by NayamAmarshe** [comment]
> As of v2.8.6 today, the same issue persists for me.
> 
> I set the scale to 2x in settings, upscale a single image and all is good. Then the same 2x setting but in a batch, and the results are in 4x instead.

I can't reproduce this issue. It works fine for me.

**Comment by iamgabereal** [comment]
For anyone still having an issue after just updating alone, I had to uninstall completely and get rid of all registry and leftover files. Then do a fresh install of v2.8.6 and all works okay now.

**Comment by aaronliu0130** [comment]
That... doesn't make sense. Great to hear it worked!

**Comment by aaronliu0130** [comment]
@dotxyzgaming Please tell us if

**Comment by F1reSt0rm83** [comment]
Hello everyone.
I want to highlight that the batch upscale still doesn't work properly, and it let me upscale only at 4x.
Any other selection still does not work.
I'm now using version 2.9.8, but the issue is the same as described in this topic so far.
I've attempted to uninstall also using 3rd party software like Revo Uninstaller Pro to remove any leftover folder and registry keys, then doing a clean install. Nothing works.
I'm using Ultrasharp mode, on an Intel Core i9 12900HX 14 cores, Geforce 3080Ti Laptop, 64 GB RAM.

**Comment by NayamAmarshe** [comment]
> Hello everyone.
> I want to highlight that the batch upscale still doesn't work properly, and it let me upscale only at 4x.
> Any other selection still does not work.
> I'm now using version 2.9.8, but the issue is the same as described in this topic so far.
> I've attempted to uninstall also using 3rd party software like Revo Uninstaller Pro to remove any leftover folder and registry keys, then doing a clean install. Nothing works.
> I'm using Ultrasharp mode, on an Intel Core i9 12900HX 14 cores, Geforce 3080Ti Laptop, 64 GB RAM.

Are you sure you waited for the batch upscale process to finish completely? or are you stopping it in the middle and looking at the files? Because the batch process progress area clearly mentions something.

**Comment by NayamAmarshe** [comment]
> > > Hello everyone.
> > > I want to highlight that the batch upscale still doesn't work properly, and it let me upscale only at 4x.
> > > Any other selection still does not work.
> > > I'm now using version 2.9.8, but the issue is the same as described in this topic so far.
> > > I've attempted to uninstall also using 3rd party software like Revo Uninstaller Pro to remove any leftover folder and registry keys, then doing a clean install. Nothing works.
> > > I'm using Ultrasharp mode, on an Intel Core i9 12900HX 14 cores, Geforce 3080Ti Laptop, 64 GB RAM.
> > 
> > 
> > Are you sure you waited for the batch upscale process to finish completely? or are you stopping it in the middle and looking at the files? Because the batch process progress area clearly mentions something.
> 
> Hi. You're right. I stopped the process midway to check the result since there were many files in the folder, and I didn't want to wait, so I missed the point. I honestly thought "the image will be resized after the process" meant it was resizing the file at the end of its process, before moving to the next one, so I thought that the process was broken. Instead, first, it upscales every single file in the folder at 4x, and only after it finishes them all, it resizes them back to the size you've selected. If you stop the process midway, ALL the files processed until that moment will remain at 4x size. I recommend editing the message on the screen to specify "......after the upscaling process **of the entire folder**", to avoid confusion. Now it's clear. Thanks, Nayam.

Thanks for the feedback! I'll make the message more clear in the future versions :) Glad that it's sorted!
